name: EssentialsPE
main: EssentialsPE\Loader
version: 2.0.0
api: 2.0.0
author: LegendsOfMCPE Team
website: https://github.com/LegendOfMCPE/EssentialsPE

permissions:
    essentials:
        default: false
        description: "Allow to access to every EssentialsPE feature"
        children:
            essentials.ban:
                default: false
                description: "Ban utilities nodes"
                children:
                    essentials.ban.exempt:
                        default: op
                        description: "Prevent the player from being banned"
            essentials.antioch:
                default: op
                description: "Place live TNT at the spot you're looking at"
            essentials.bigtree:
                default: op
                description: "Spawns a big tree"
            essentials.break:
                default: false
                description: "Breaks the block you're looking at"
                children:
                    essentials.break.use:
                        default: op
                        description: "Breaks the block you're looking at"
                    essentials.break.bedrock:
                        default: op
                        description: "Allow to break Bedrock"
            essentials.broadcast:
                default: op
                description: "Broadcast a message"
            essentials.burn:
                default: op
                description: "Set a player on fire"
            essentials.compass:
                default: true
                description: "Display your current bearing direction"
            essentials.condense:
                default: true
                description: "Compact items into blocks in your inventory!"
            essentials.depth:
                default: true
                description: "Get your current height related to sea-level"
            essentials.essentials:
                default: op
                description: "See the current Essentials version"
            essentials.extinguish:
                default: false
                description: "Extinguish a player"
                children:
                    essentials.extinguish.use:
                        default: op
                        description: "Extinguish yourself"
                    essentials.extinguish.other:
                        default: op
                        description: "Extinguish other players"
            essentials.gamemode:
                default: op
                description: "Change your gamemode!"
            essentials.geoip:
                default: false
                description: "GeoLocation nodes"
                children:
                    essentials.geoip.show:
                        default: op
                        description: "See other's location in the real world"
                    essentials.geoip.hide:
                        default: false
                        description: "Hide location from other users that 'have' permissions to see it"
            essentials.getpos:
                default: false
                description: "Get any player's position"
                children:
                    essentials.getpos.use:
                        default: op
                        description: "Get your position"
                    essentials.getpos.other:
                        default: op
                        description: "Get other player's position"
            essentials.god:
                default: false
                description: "Prevent a player to take any damage"
                children:
                    essentials.god.use:
                        default: op
                        description: "Prevent you to take damage"
                    essentials.god.other:
                        default: op
                        description: "Prevent other players to take damage"
                    essentials.god.pvp:
                        default: op
                        description: "Let you attack other players while you're in god mode"
            essentials.hat:
                default: op
                description: "Get some new cool headgear!"
            essentials.item:
                default: op
                description: "Gives yourself an item"
            essentials.itemdb:
                default: op
                description: "Let you see information attached to an item"
            essentials.itemspawn:
                default: op
                description: "Let you spawn any item using /item"
                children:
                    essentials.itemspawn.item-all:
                        default: op
                        description: "Let you spawn any item"
                    #essentials.itemspawn.exempt:
                    #    default: op
                    #    description: "Allow the spawning of blacklisted items"
            essentials.jump:
                default: op
                description: "Teleport you to the block you're looking at"
            essentials.kickall:
                default: op
                description: "Kick all the online players except the sender"
            essentials.kill:
                default: false
                description: "Kill a player!"
                children:
                    essentials.kill.use:
                        default: op
                        description: "Commit to suicide"
                    essentials.kill.other:
                        default: op
                        description: "Kill other players"
            essentials.more:
                default: op
                description: "Get a stack of the item you're holding"
            essentials.msg:
                default: true
                description: "Send private messages to other players"
            essentials.mute:
                default: false
                description: "Mute a player from the chat"
                chldren:
                    essentials.mute.use:
                        default: op
                        description: "Mute a player from the chat"
                    essentials.mute.exempt:
                        default: op
                        description: "Prevent a player from being muted"
                    essentials.mute.notify:
                        default: true
                        description: "Tell a user until when is muted from the chat"
            essentials.near:
                default: false
                description: "Let you search for near players"
                children:
                    essentials.near.use:
                        default: op
                        description: "Display players near to you"
                    essentials.near.other:
                        default: op
                        description: "Let you see who is near to another player"
            essentials.oversizedstacks:
                default: op
                description: "Allow to get oversized stacks"
            essentials.pay:
                default: true
                description: "Pay another player from your balance"
            essentials.powertool:
                default: false
                description: "Allow to toggle and use PowerTool"
                children:
                    essentials.powertool.use:
                        default: op
                        description: "Access the /powertool command"
                    essentials.powertool.append:
                        default: op
                        description: "Let you add multiple commands to the PowerTool"
            essentials.powertooltoggle:
                default: op
                description: "Allow to disable PowerTool from all the items (of a player)"
            essentials.ptime:
               default: false
               description: "Change your current time!"
               children:
                    essentials.ptime.use:
                        default: op
                        description: "Change your own time"
                    essentials.ptime.other:
                        default: op
                        description: "Change other's time"
            essentials.pvp:
                default: op
                description: "Toggle PvP on/off"
            essentials.repair:
                default: false
                description: "Repair the item you're holding"
                children:
                    essentials.repair.use:
                        default: op
                        description: "Access the /repair command"
                    essentials.repair.all:
                        default: op
                        description: "Let you repair all the damaged tools/armors on your inventory"
                    essentials.repair.armor:
                        default: op
                        description: "Let your repair the equipped armor while using /repair all"
            essentials.reply:
                default: true
                description: "Allow the player to quick reply to the last player that messaged him"
            essentials.seen:
                default: op
                description: "Check player's last online time"
            essentials.setworth:
                default: op
                description: "Sets the worth of an item"
            essentials.sudo:
                default: false
                description: "Run a command as another player"
                children:
                    essentials.sudo.use:
                        default: op
                        description: "Run a command as another player"
                    essentials.sudo.exempt:
                        default: false
                        description: "Prevent from being Sudo'ed"
            essentials.suicide:
                default: op
                description: "Kill yourself"
            essentials.tpall:
                default: op
                description: "Teleport all the online players to you"
            essentials.tempban:
                default: op
                description: "Temporary bans a player"
            essentials.top:
                default: op
                description: "Teleport to the highest block above you"
            essentials.tree:
                default: op
                description: "Spawns a tree"
            essentials.unlimited:
                default: false
                description: "Allow the player to place unlimited blocks"
                children:
                    essentials.unlimited.use:
                        default: op
                        description: "Access the /unlimited command"
                    essentials.unlimited.other:
                        default: op
                        description: "Allow to enable unlimited placing of blocks to other players"
            essentials.update:
                default: false
                description: "Allow to update EssentialsPE to the latest available version, or to check if there is one available"
                children:
                    essentials.update.use:
                        default: op
                        description: "Allow to update EssentialsPE with the '/essentials update' command "
                    essentials.update.notify:
                        default: op
                        description: "Get notified when a new version of EssentialsPE if found"
            essentials.vanish:
                default: false
                description: "Hide yourself or another player"
                children:
                    essentials.vanish.use:
                        default: op
                        description: "Hide yourself from other players"
                    essentials.vanish.other:
                        default: op
                        description: "Hide other players"
                    essentials.vanish.pvp:
                        default: op
                        description: "Let you attack other players while you're vanished"
            essentials.whois:
                default: true
                description: "Display information about a player"
            essentials.world:
                default: op
                description: "Teleport to another world"
            essentials.worth:
                default: true
                description: "Get the price of an item"
